import type { Metadata } from "next";
import "./globals.css";
import NavbarSignup from "@/components/layouts/NavbarSignup";
import NavbarSignin from "@/components/layouts/NavbarSignin";

export const metadata: Metadata = {
  title: "Find Job",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="min-h-screen w-full">
          {/* <NavbarSignin /> */}
          {/* <NavbarSignup /> */}

          <main className="border">
            <div className="">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
