import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Job Every",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="min-h-screen w-full">
          <main className="">
            <div className="">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
